tasks:
  hello-job:
    runner: sonarsource/sonar-scanner-cli
    steps:
   
    - checkout    
    - commands:
      - |
        sonar-scanner \
         -Dsonar.projectKey=golang \
         -Dsonar.sources=. \
         -Dsonar.host.url=http://13.233.126.85:9000 \
         -Dsonar.login=b91519483c42f6d5c13be49acdc973b3e7a214dc
